#!/bin/bash

echo "🔄 GitHub Manual Sync Guide"
echo "=========================="
echo ""
echo "1. GitHub Repository'yi Aç:"
echo "   https://github.com/orhannurkan/v0-cursor-refactored-v15/tree/develop"
echo ""
echo "2. Son Commit'leri Kontrol Et:"
echo "   - 'Commits' sekmesine tıkla"
echo "   - Son 5-10 commit'i incele"
echo "   - Hangi dosyaların değiştiğini gör"
echo ""
echo "3. Değişen Dosyaları Kopyala:"
echo "   - Değişen dosyayı GitHub'da aç"
echo "   - 'Raw' butonuna tıkla"
echo "   - İçeriği kopyala"
echo "   - v0'da ilgili dosyayı güncelle"
echo ""
echo "4. Yaygın Değişen Dosyalar:"
echo "   - app/page.tsx"
echo "   - app/layout.tsx"
echo "   - README.md"
echo "   - components/ui/*.tsx"
echo "   - package.json"
echo ""
echo "5. Güncelleme Sonrası:"
echo "   - Projeyi test et"
echo "   - Hataları kontrol et"
echo "   - Gerekirse düzeltmeler yap"
echo ""
echo "✅ Sync tamamlandığında bu guide'ı tekrar çalıştırabilirsin"
